using System;
using LifeSim.Imago.Generators.Analysis;
using LifeSim.Imago.Generators.Diagnostics;
using LifeSim.Imago.Generators.Emitting;
using LifeSim.Imago.Generators.Parsing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace LifeSim.Imago.Generators;

/// <summary>
/// Source generator that compiles .template.xml files into C# code-behind.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class TemplateGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var templates = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".template.xml", System.StringComparison.OrdinalIgnoreCase));

        // TODO: Combining with CompilationProvider means any source file change re-triggers
        // all template processing. At ~30 templates this is negligible, but if template count
        // grows significantly, refactor to extract only needed symbols via CreateSyntaxProvider.
        var templatesWithCompilation = templates
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(
            templatesWithCompilation,
            static (spc, pair) => Execute(spc, pair.Left, pair.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        AdditionalText templateFile,
        Compilation compilation)
    {
        var text = templateFile.GetText(context.CancellationToken);
        if (text == null)
        {
            return;
        }

        try
        {
            var langVersion = ((CSharpCompilation)compilation).LanguageVersion;
            var tree = TemplateParser.Parse(text.ToString(), templateFile.Path);
            context.CancellationToken.ThrowIfCancellationRequested();
            var analyzed = TemplateAnalyzer.Analyze(tree, compilation);
            context.CancellationToken.ThrowIfCancellationRequested();
            var code = CodeEmitter.Emit(analyzed, langVersion);
            context.AddSource(analyzed.ClassName + ".g.cs", code);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (TemplateDiagnosticException ex)
        {
            context.ReportDiagnostic(ex.CreateDiagnostic());
            TryEmitStub(context, templateFile.Path, compilation);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InternalError, Location.None, templateFile.Path, ex.Message));
            TryEmitStub(context, templateFile.Path, compilation);
        }
    }

    /// <summary>
    /// Emits a stub partial class with an empty LoadTemplate() so that template errors
    /// don't cascade into CS1061 errors in the code-behind.
    /// </summary>
    private static void TryEmitStub(
        SourceProductionContext context,
        string filePath,
        Compilation compilation)
    {
        try
        {
            var fileName = System.IO.Path.GetFileName(filePath);
            var shortName = fileName.EndsWith(".template.xml", StringComparison.OrdinalIgnoreCase)
                ? fileName.Substring(0, fileName.Length - ".template.xml".Length)
                : System.IO.Path.GetFileNameWithoutExtension(fileName);

            var candidates = compilation.GetSymbolsWithName(shortName, SymbolFilter.Type);
            foreach (var symbol in candidates)
            {
                if (symbol is INamedTypeSymbol namedType)
                {
                    var ns = namedType.ContainingNamespace.ToDisplayString();
                    var stub =
                        "// <auto-generated />\n" +
                        $"namespace {ns};\n\n" +
                        $"partial class {shortName}\n" +
                        "{\n" +
                        "    private void LoadTemplate() { }\n" +
                        "}\n";

                    context.AddSource(ns + "." + shortName + ".g.cs", stub);
                    return;
                }
            }
        }
        catch
        {
            // Stub emission is best-effort; the real diagnostic was already reported.
        }
    }
}
