using System.Collections.Generic;
using System.Linq;
using Imago.Generators.Analysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Imago.Generators.Emitting;

/// <summary>
/// Generates C# source code from an analyzed template tree.
/// </summary>
internal static class CodeEmitter
{
    /// <summary>
    /// Emits the complete C# source file for a template.
    /// </summary>
    /// <param name="tree">The fully analyzed template tree.</param>
    /// <param name="langVersion">The C# language version of the consuming project.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Emit(AnalyzedTree tree, LanguageVersion langVersion)
    {
        var useEnhancedLine = langVersion >= LanguageVersion.CSharp10;
        var w = new SourceWriter(tree.FilePath, useEnhancedLine);

        // Header
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");

        // Using directives from xmlns
        var namespaces = new HashSet<string>();
        foreach (var ns in tree.NamespaceMap.GetAllNamespaces())
        {
            namespaces.Add(ns);
        }

        // Always include the class's own namespace
        namespaces.Add(tree.Namespace);

        var sortedNamespaces = new List<string>(namespaces);
        sortedNamespaces.Sort();

        foreach (var ns in sortedNamespaces)
        {
            w.WriteLine($"using {ns};");
        }

        w.WriteLine();

        // Namespace and class declaration
        w.WriteLine($"namespace {tree.Namespace};");
        w.WriteLine();
        w.WriteLine($"public partial class {tree.ShortClassName}");
        w.WriteLine("{");
        w.Indentation++;

        EmitClassBody(w, tree.Root);

        // Nested class definitions
        foreach (var nested in tree.NestedClasses)
        {
            w.WriteLine();
            w.WriteLine($"partial class {nested.ShortClassName}");
            w.WriteLine("{");
            w.Indentation++;

            EmitClassBody(w, nested.Root);

            w.Indentation--;
            w.WriteLine("}");
        }

        w.Indentation--;
        w.WriteLine("}");

        return w.ToString();
    }

    private static void EmitClassBody(SourceWriter w, AnalyzedNode root)
    {
        var fields = root.GetNamedDescendants();

        // Collect factory templates and assign indices during variable assignment
        var factoryTemplates = new List<AnalyzedNode>();

        // Assign variable names (post-order traversal)
        var counter = 0;
        AssignVariableNames(root, ref counter, isRoot: true, factoryTemplates);

        // Collect unnamed elements with bindings (need to be promoted to fields)
        var boundUnnamedNodes = new List<AnalyzedNode>();
        CollectBoundUnnamedNodes(root, boundUnnamedNodes, isRoot: true);
        var promotedFields = new HashSet<string>();
        foreach (var node in boundUnnamedNodes)
        {
            promotedFields.Add(node.VariableName);
        }

        // Field declarations
        foreach (var field in fields)
        {
            w.WriteLine($"private {field.ResolvedTypeName} {field.FieldName} = null!;");
        }

        foreach (var node in boundUnnamedNodes)
        {
            w.WriteLine($"private {node.ResolvedTypeName} {node.VariableName} = null!;");
        }

        if (fields.Count > 0 || boundUnnamedNodes.Count > 0)
        {
            w.WriteLine();
        }

        // LoadTemplate method
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Initializes the control tree declared in the associated template file.");
        w.WriteLine("/// </summary>");
        w.WriteLine("private void LoadTemplate()");
        w.WriteLine("{");
        w.Indentation++;

        // Root element properties
        foreach (var prop in root.Properties)
        {
            w.WriteLine(prop.Span, $"this.{prop.PropertyName} = {prop.Expression};");
        }

        if (root.Properties.Count > 0)
        {
            w.WriteLine();
        }

        // Root element events
        foreach (var evt in root.Events)
        {
            w.WriteLine(evt.Span, $"this.{evt.EventName} += {evt.HandlerExpression};");
        }

        if (root.Events.Count > 0)
        {
            w.WriteLine();
        }

        // Child elements (post-order: leaves first)
        EmitStatements(w, root, isRoot: true, promotedFields);

        w.Indentation--;
        w.WriteLine("}");

        // Factory methods
        EmitFactoryMethods(w, factoryTemplates);

        // Binding method
        var allBindings = new List<AnalyzedBinding>();
        CollectBindings(root, allBindings, isRoot: true);

        if (allBindings.Count > 0)
        {
            EmitActivateTemplateBindings(w, allBindings);
        }
    }

    private static void AssignVariableNames(
        AnalyzedNode node,
        ref int counter,
        bool isRoot,
        List<AnalyzedNode> factoryTemplates)
    {
        // Post-order: children first, but skip factory template body children
        // (they get their own scoped names during factory method emission)
        if (!node.IsFactoryTemplate)
        {
            foreach (var child in node.Children)
            {
                AssignVariableNames(child, ref counter, isRoot: false, factoryTemplates);
            }
        }

        foreach (var propChildren in node.PropertyElements.Values)
        {
            foreach (var child in propChildren)
            {
                AssignVariableNames(child, ref counter, isRoot: false, factoryTemplates);
            }
        }

        if (!isRoot)
        {
            if (node.IsFactoryTemplate)
            {
                factoryTemplates.Add(node);
            }

            node.VariableName = "__e" + counter;
            counter++;
        }
    }

    private static void EmitStatements(SourceWriter w, AnalyzedNode node, bool isRoot, HashSet<string>? promotedFields = null)
    {
        // Post-order: emit children first (skip factory template body children)
        if (!node.IsFactoryTemplate)
        {
            foreach (var child in node.Children)
            {
                EmitStatements(w, child, isRoot: false, promotedFields);
            }
        }

        foreach (var propChildren in node.PropertyElements.Values)
        {
            foreach (var child in propChildren)
            {
                EmitStatements(w, child, isRoot: false, promotedFields);
            }
        }

        if (!isRoot)
        {
            // Factory templates use the generated method reference as the constructor arg
            var ctor = node.IsFactoryTemplate
                ? $"(this.__CreateFactory_{node.VariableName})"
                : node.ConstructorArguments != null
                    ? $"({node.ConstructorArguments})"
                    : "";

            // Unnamed elements with bindings are promoted to fields
            var isPromoted = promotedFields != null && promotedFields.Contains(node.VariableName);
            var declaration = isPromoted ? $"this.{node.VariableName}" : $"var {node.VariableName}";

            w.WriteLine(node.ElementSpan, $"{declaration} = new {node.ResolvedTypeName}{ctor}");
            w.WriteLine("{");
            w.Indentation++;

            // Set Visual.Name if the type has the property
            if (node.Name != null && node.HasNameProperty)
            {
                w.WriteLine($"Name = \"{node.Name}\",");
            }

            // Other properties
            foreach (var prop in node.Properties)
            {
                w.WriteLine(prop.Span, $"{prop.PropertyName} = {prop.Expression},");
            }

            w.Indentation--;
            w.WriteLine("};");

            // Field assignment if named
            if (node.FieldName != null)
            {
                w.WriteLine($"this.{node.FieldName} = {node.VariableName};");
            }

            // Event subscriptions
            foreach (var evt in node.Events)
            {
                w.WriteLine(evt.Span, $"{node.VariableName}.{evt.EventName} += {evt.HandlerExpression};");
            }

            w.WriteLine();
        }

        // Emit child additions (after children have been created)
        EmitChildAdditions(w, node, isRoot);
    }

    private static void EmitChildAdditions(SourceWriter w, AnalyzedNode parent, bool isRoot)
    {
        var prefix = isRoot ? "this" : parent.VariableName;

        // Property element children
        foreach (var kvp in parent.PropertyElements)
        {
            var propertyName = kvp.Key;
            var children = kvp.Value;

            if (children.Count == 1)
            {
                w.WriteLine(children[0].ElementSpan, $"{prefix}.{propertyName} = {children[0].VariableName};");
            }
            else
            {
                foreach (var child in children)
                {
                    w.WriteLine(child.ElementSpan, $"{prefix}.{propertyName}.Add({child.VariableName});");
                }
            }
        }

        // Regular children via Items or Content (not applicable for factory templates)
        if (!parent.IsFactoryTemplate && parent.Children.Count > 0)
        {
            if (parent.ChildSlot == ChildSlot.Items)
            {
                foreach (var child in parent.Children)
                {
                    w.WriteLine(child.ElementSpan, $"{prefix}.{parent.ChildSlotPropertyName}.Add({child.VariableName});");
                }
            }
            else if (parent.ChildSlot == ChildSlot.Content)
            {
                w.WriteLine(parent.Children[0].ElementSpan, $"{prefix}.{parent.ChildSlotPropertyName} = {parent.Children[0].VariableName};");
            }
        }

        // Text content assignment
        if (parent.TextContent != null && parent.TextPropertyName != null)
        {
            var escaped = SymbolHelpers.EscapeCSharpString(parent.TextContent);
            w.WriteLine($"{prefix}.{parent.TextPropertyName} = \"{escaped}\";");
        }
    }

    private static void EmitFactoryMethods(SourceWriter w, List<AnalyzedNode> factoryTemplates)
    {
        foreach (var factory in factoryTemplates)
        {
            var info = factory.FactoryInfo!;

            w.WriteLine();
            w.WriteLine("[System.Runtime.CompilerServices.CompilerGenerated]");
            w.WriteLine("[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
            w.WriteLine($"private {info.ReturnTypeName} __CreateFactory_{factory.VariableName}({info.ParameterTypeName} {info.ParameterName})");
            w.WriteLine("{");
            w.Indentation++;

            // Assign scoped variable names for the factory body
            var factoryCounter = 0;
            var emptyList = new List<AnalyzedNode>();
            var factoryRoot = factory.Children[0];
            AssignVariableNames(factoryRoot, ref factoryCounter, isRoot: false, emptyList);

            // Emit the factory body subtree (EmitStatements handles children + child additions)
            EmitStatements(w, factoryRoot, isRoot: false);

            w.WriteLine($"return {factoryRoot.VariableName};");

            w.Indentation--;
            w.WriteLine("}");
        }
    }

    private static void CollectBindings(AnalyzedNode node, List<AnalyzedBinding> bindings, bool isRoot)
    {
        // Root element targets "this", named elements use "this.{fieldName}",
        // unnamed elements use "this.{variableName}" (promoted to fields)
        string targetVar;
        if (isRoot)
        {
            targetVar = "this";
        }
        else if (node.FieldName != null)
        {
            targetVar = "this." + node.FieldName;
        }
        else
        {
            targetVar = "this." + node.VariableName;
        }

        foreach (var binding in node.Bindings)
        {
            binding.TargetVariable = targetVar;
            bindings.Add(binding);
        }

        // Skip factory template body children (they have their own scope)
        if (!node.IsFactoryTemplate)
        {
            foreach (var child in node.Children)
            {
                CollectBindings(child, bindings, isRoot: false);
            }
        }

        foreach (var propChildren in node.PropertyElements.Values)
        {
            foreach (var child in propChildren)
            {
                if (!child.IsFactoryTemplate)
                {
                    CollectBindings(child, bindings, isRoot: false);
                }
            }
        }
    }

    private static void CollectBoundUnnamedNodes(AnalyzedNode node, List<AnalyzedNode> result, bool isRoot)
    {
        if (!isRoot && node.FieldName == null && node.Bindings.Count > 0)
        {
            result.Add(node);
        }

        if (!node.IsFactoryTemplate)
        {
            foreach (var child in node.Children)
            {
                CollectBoundUnnamedNodes(child, result, isRoot: false);
            }
        }

        foreach (var propChildren in node.PropertyElements.Values)
        {
            foreach (var child in propChildren)
            {
                if (!child.IsFactoryTemplate)
                {
                    CollectBoundUnnamedNodes(child, result, isRoot: false);
                }
            }
        }
    }

    private static void EmitActivateTemplateBindings(SourceWriter w, List<AnalyzedBinding> bindings)
    {
        w.WriteLine();
        w.WriteLine("/// <inheritdoc />");
        w.WriteLine("[System.Runtime.CompilerServices.CompilerGenerated]");
        w.WriteLine("[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
        w.WriteLine("protected override System.IDisposable? ActivateTemplateBindings()");
        w.WriteLine("{");
        w.Indentation++;

        // Initial assignments
        foreach (var binding in bindings)
        {
            w.WriteLine(FormatBindingStatement(binding));
        }

        w.WriteLine();

        // Group bindings by source key
        var groups = bindings
            .GroupBy(b => b.SourceKey)
            .ToList();

        // Emit one handler per source
        foreach (var group in groups)
        {
            var sourceKey = group.Key;
            var handlerName = "__bind_" + SanitizeHandlerName(sourceKey);
            var sourceExpr = group.First().SourceExpression;
            var groupBindings = group.ToList();

            w.WriteLine($"void {handlerName}(object? __s, System.ComponentModel.PropertyChangedEventArgs __e)");
            w.WriteLine("{");
            w.Indentation++;

            if (groupBindings.Count == 1)
            {
                var b = groupBindings[0];
                w.WriteLine($"if (__e.PropertyName is null or \"\" or nameof({b.AssignExpression}))");
                w.Indentation++;
                w.WriteLine(FormatBindingStatement(b));
                w.Indentation--;
            }
            else
            {
                w.WriteLine("if (string.IsNullOrEmpty(__e.PropertyName))");
                w.WriteLine("{");
                w.Indentation++;

                foreach (var b in groupBindings)
                {
                    w.WriteLine(FormatBindingStatement(b));
                }

                w.Indentation--;
                w.WriteLine("}");
                w.WriteLine("else switch (__e.PropertyName)");
                w.WriteLine("{");
                w.Indentation++;

                foreach (var b in groupBindings)
                {
                    w.WriteLine($"case nameof({b.AssignExpression}): {FormatBindingStatement(b)} break;");
                }

                w.Indentation--;
                w.WriteLine("}");
            }

            w.Indentation--;
            w.WriteLine("}");
            w.WriteLine();
        }

        // Subscribe
        foreach (var group in groups)
        {
            var handlerName = "__bind_" + SanitizeHandlerName(group.Key);
            var sourceExpr = group.First().SourceExpression;
            w.WriteLine($"{sourceExpr}.PropertyChanged += {handlerName};");
        }

        w.WriteLine();

        // Return disposable
        w.WriteLine("return new Imago.Controls.TemplateBindingDisposable(() =>");
        w.WriteLine("{");
        w.Indentation++;

        foreach (var group in groups)
        {
            var handlerName = "__bind_" + SanitizeHandlerName(group.Key);
            var sourceExpr = group.First().SourceExpression;
            w.WriteLine($"{sourceExpr}.PropertyChanged -= {handlerName};");
        }

        w.Indentation--;
        w.WriteLine("});");

        w.Indentation--;
        w.WriteLine("}");
    }

    private static string FormatBindingStatement(AnalyzedBinding b)
    {
        if (b.IsMethodTarget)
        {
            return $"{b.TargetVariable}.{b.TargetProperty}({b.AssignExpression});";
        }

        return $"{b.TargetVariable}.{b.TargetProperty} = {b.AssignExpression};";
    }

    private static string SanitizeHandlerName(string sourceKey)
    {
        // "this" -> "this", "_vm" -> "vm", "_theme" -> "theme"
        var name = sourceKey;
        if (name.StartsWith("_"))
        {
            name = name.Substring(1);
        }

        // Replace dots with underscores for nested access paths
        return name.Replace(".", "_");
    }
}
