using LifeSim.Support.Collections;
using LifeSim.Support.Numerics;

namespace LifeSim.Imago.TexturePacking;

// Based in "A Thousand Ways to Pack the Bin - A Practical Approach to Two-Dimensional Rectangle Bin Packing" (2010)
// It uses a GUILLOTINE-MINAS-BAF heuristic (Guillotine algorithm, Min area split, Best Area fit)

/// <summary>
/// The BinPacker class is used to pack Rectangles into a single Rectangle. This class does not operates with
/// textures, only with rectangles.
/// </summary>
public class BinPacker
{
    private readonly SwapPopList<Node> _freeList;
    private uint _freeArea;

    /// <summary>
    /// Initializes a new instance of the <see cref="BinPacker"/> class.
    /// </summary>
    /// <param name="width">The total width of the container rectangle.</param>
    /// <param name="height">The total height of the container rectangle.</param>
    public BinPacker(uint width, uint height)
    {
        this._freeList = new SwapPopList<Node>(4);
        this._freeArea = width * height;
        this._freeList.Add(new Node(0, 0, width, height));
    }

    /// <summary>
    /// Gets whether the bin is full.
    /// </summary>
    public bool IsFull => this._freeArea == 0;

    /// <summary>
    /// Try to insert a rectangle into the bin. Returns whether the rectangle was successfully inserted.
    /// </summary>
    /// <param name="width">The width of the rectangle.</param>
    /// <param name="height">The height of the rectangle.</param>
    /// <param name="coords">The coorddinates where the rectangle was inserted.</param>
    /// <returns>Whether the rectangle was successfully inserted.</returns>
    public bool TryFit(uint width, uint height, out Vector2Int coords)
    {
        int nodeIndex = this.FindFreeSpaceIndex(width, height);
        if (nodeIndex == -1)
        {
            coords = Vector2Int.Zero;
            return false;
        }

        coords = new Vector2Int(this._freeList[nodeIndex].X, this._freeList[nodeIndex].Y);
        this.InsertAt(nodeIndex, width, height);
        return true;
    }

    private void InsertAt(int nodeIndex, uint width, uint height)
    {
        Node node = this._freeList[nodeIndex];
        this._freeArea -= width * height;
        // If the rectangle fits perfectly, we don't generate any split (Early exit)
        if (node.Width == width && node.Height == height)
        {
            this._freeList.RemoveAt(nodeIndex);
            return;
        }

        // 3 imaginary sub rectangles are generated by the split. (<A1> right, <A2> bottom and <A3> bottom right)
        // We define the right <A1> and bottom <A2> rectangles and then we will expand one of those two rectangles
        // to cover the <A3> rectangle. The strategy for selecting which one to expand is described in the paper
        // as the "Min Area Split" rule (-MINAS).
        var right  = new Node( node.X + width, node.Y         , node.Width - width, height               );
        var bottom = new Node( node.X        , node.Y + height, width             , node.Height - height );

        // We use the "Min Area Split" rule. (-MINAS). This means we join A3 with the
        // larger of A1 and A2 to produce a single larger free rectangle.
        if (right.Area > bottom.Area)
        {
            right.Height = node.Height;
            right.Area = right.Width * right.Height;
        }
        else
        {
            bottom.Width = node.Width;
            bottom.Area = bottom.Width * bottom.Height;
        }

        // Then we need to update our free list accordingly. If any of the sub rectangles
        // has a non-zero area, we need to add it to the free list. We reuse the same indexes
        // in the list to avoid reallocating the list.
        if (right.Area != 0)
        {
            this._freeList[nodeIndex] = right;
            if (bottom.Area != 0)
                this._freeList.Add(bottom);
        }
        else if (bottom.Area != 0)
        {
            this._freeList[nodeIndex] = bottom;
        }
        else
        {
            this._freeList.RemoveAt(nodeIndex);
        }
    }

    private int FindFreeSpaceIndex(uint width, uint height)
    {
        // We use the "Best Area Fit" rule (-BAF)
        uint rectArea = width * height;
        if (this._freeArea < rectArea) return -1;

        uint minWastedArea = int.MaxValue;
        int minWastedIndex = -1;

        for (int i = 0; i < this._freeList.Count; i++)
        {
            Node node = this._freeList[i];
            if (width <= node.Width && height <= node.Height)
            {
                uint wastedArea = node.Area - rectArea;

                if (wastedArea < minWastedArea)
                {
                    if (wastedArea == 0) return i;
                    minWastedArea = wastedArea;
                    minWastedIndex = i;
                }
            }
        }

        return minWastedIndex;
    }

    /// <summary>
    /// Releases a rectangle from the bin.
    /// </summary>
    /// <param name="width">The width of the rectangle.</param>
    /// <param name="height">The height of the rectangle.</param>
    /// <param name="coords">The coordinates of the rectangle.</param>
    public void Release(Vector2Int coords, Vector2Int size)
    {
        this._freeArea += (uint)(size.X * size.Y);
        this._freeList.Add(new Node((uint)coords.X, (uint)coords.Y, (uint)size.X, (uint)size.Y));
    }

    private struct Node
    {
        public uint X;
        public uint Y;
        public uint Width;
        public uint Height;
        public uint Area;

        public Node(uint x, uint y, uint width, uint height)
        {
            this.X = x;
            this.Y = y;
            this.Width = width;
            this.Height = height;
            this.Area = width * height;
        }
    }
}
